name: Build and Release

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Build binary with Docker
      run: ./build-docker.sh
    
    - name: Test binary
      run: |
        chmod +x ./gitlab-mcp-server-ubuntu
        echo '{"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {"protocolVersion": "2024-11-05", "capabilities": {"tools": {}}, "clientInfo": {"name": "test-client", "version": "1.0"}}}' | timeout 10s ./gitlab-mcp-server-ubuntu || true
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: gitlab-mcp-server-ubuntu
        path: gitlab-mcp-server-ubuntu
        retention-days: 30
    
    - name: Create Release and Upload Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: ./gitlab-mcp-server-ubuntu