name: Build Linux Binary

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Linux binary
      run: |
        pyinstaller --onefile --name gitlab-mcp-server-linux mcp_server.py
    
    - name: Test Linux binary
      run: |
        echo '{"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {"protocolVersion": "2024-11-05", "capabilities": {"tools": {}}, "clientInfo": {"name": "test-client", "version": "1.0"}}}' | ./dist/gitlab-mcp-server-linux
    
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: gitlab-mcp-server-linux
        path: dist/gitlab-mcp-server-linux
        retention-days: 30

  create-release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: gitlab-mcp-server-linux
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gitlab-mcp-server-linux
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
